name: Frontend CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Берём версию pnpm из package.json и активируем через corepack
      - name: Detect pnpm version from package.json
        id: pnpmver
        run: |
          echo "PNPM_VERSION=$(node -p "require('./package.json').packageManager.split('@')[1]")" >> $GITHUB_ENV
          echo "Using pnpm ${PNPM_VERSION}"

      - name: Enable corepack (activate exact pnpm)
        run: |
          corepack enable
          corepack prepare pnpm@${PNPM_VERSION} --activate
          pnpm -v

      # Кэшируем pnpm store
      - name: Get pnpm store path
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: pnpm-store-${{ env.PNPM_VERSION }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-store-${{ env.PNPM_VERSION }}-
            pnpm-store-

      - name: Install deps
        run: pnpm install --frozen-lockfile=false

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Build
        env:
          CI: true
        run: pnpm build
